name: Build and Deploy using docker-compose

on:
  push:
    branches:
      - main

env:
  DEPLOY_HOME: /home/admin/deploy
  TEMPLATES_REPO: moonai-vn/cicd-template
  TEMPLATES_PATH: cicd-tempalte
  COMPOSE_TEMPLATE: docker-compose/docker-compose.yaml
  

jobs:      
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Set variables
        id: vars
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | sed 's/\//-/g')
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
          echo "DEPLOY_DIR=${DEPLOY_HOME}/${REPO_NAME}" >> $GITHUB_ENV
          
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          path: application

      - name: Checkout central templates
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TEMPLATES_REPO }}
          path: ${{ env.TEMPLATES_PATH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        working-directory: application
        run: |
          docker build -t ${REPO_NAME}:${BRANCH_NAME}-${COMMIT_HASH} .

      - name: Deploy with docker-compose
        run: |
          # Create deployment directory if it doesn't exist
          mkdir -p ${DEPLOY_DIR}
          # Copy central Docker Compose template from templates directory
          cp ${TEMPLATES_PATH}/${COMPOSE_TEMPLATE} ${DEPLOY_DIR}/docker-compose.yaml
          # Deploy with docker-compose in the deployment directory
          cd ${DEPLOY_DIR}
          # Debug local environments
          echo ${GITHUB_ENV}
          docker-compose up -d

