version: '3.9'
name: moonai

x-moonai-config:
  &moonai-env
  HOST_PORT: ${HOST_PORT:-127.0.0.1:5000}
  CONTAINER_PORT: ${CONTAINER_PORT:-5000}
  MOON_AI_REGISTRY: ${MOON_AI_REGISTRY:-registry.moonai.vn}
  DB_TYPE: ${DB_TYPE}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  JWT_SECRET: ${JWT_SECRET}
  EXPIRES_ACCESS_TOKEN: ${EXPIRES_ACCESS_TOKEN}
  EXPIRES_REFRESH_TOKEN: ${EXPIRES_REFRESH_TOKEN}
  CLIENT_URL: ${CLIENT_URL}
  NEXT_PUBLIC_CLIENT_GOOGLE_ID: ${NEXT_PUBLIC_CLIENT_GOOGLE_ID}
  NEXT_PUBLIC_SERVER: ${NEXT_PUBLIC_SERVER}
  NEXT_PUBLIC_CLIENT_SECRET: ${NEXT_PUBLIC_CLIENT_SECRET}
  NEXT_PUBLIC_DEVELOPMENT_KEY: ${NEXT_PUBLIC_DEVELOPMENT_KEY}
  NEXT_PUBLIC_R2_ACCOUNT_ID: ${NEXT_PUBLIC_R2_ACCOUNT_ID}
  NEXT_PUBLIC_R2_BUCKET_NAME: ${NEXT_PUBLIC_R2_BUCKET_NAME}
  NEXT_PUBLIC_R2_URL: ${NEXT_PUBLIC_R2_URL}
  R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
  R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
  R2_SECRET_KEY_ID: ${R2_SECRET_KEY_ID}
  R2_BUCKET_NAME: ${R2_BUCKET_NAME}
  TOKEN_VALUE: ${TOKEN_VALUE}
  R2_API_TOKEN: ${R2_API_TOKEN}

services:
  app:
    container_name: ${REPO_NAME}
    image: ${MOON_AI_REGISTRY}/${REPO_NAME}:${BRANCH_NAME}-${COMMIT_HASH}
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    environment:
      <<: *moonai-env
    networks:
      - moonai_kong-net

networks:
  moonai_kong-net:
    external: true
