version: '3'
services:
  app:
    image: ${REPO_NAME}:${BRANCH_NAME}-${COMMIT_HASH}
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - ENV_VAR1=${ENV_VAR1}
      - ENV_VAR2=${ENV_VAR2}
